# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: turnbridgebackend
services:
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
  redis:
    extends:
      file: ./redis.yml
      service: redis
